# Configuration for calling services through API Gateway
spring:
  cloud:
    openfeign:
      client:
        config:
          identity-service:
            url: http://localhost:8080/identity
          course-service:
            url: http://localhost:8080/api/v1
          exam-service:
            url: http://localhost:8080/exam
          proctoring-service:
            url: http://localhost:8080/api/proctoring
